apiVersion: apps/v1
kind: Deployment
metadata:
  name: agentsapi
  namespace: dev
  labels:
    app: agentsapi
    backstage.io/kubernetes-id: agentsapi-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: agentsapi
  template:
    metadata:
      annotations:
        ad.datadoghq.com/agentsapi.logs: '[{"source":"agentsapi","service":"agentsapi"}]'
      labels:
        app: agentsapi
        backstage.io/kubernetes-id: agentsapi-app
    spec:
      containers:
      - name: agentsapi
        image: "{{IMAGE_NAME}}"
        ports:
        - containerPort: 80
