apiVersion: apps/v1
kind: Deployment
metadata:
  name: agentsapi
  labels:
    app: agentsapi
    backstage.io/kubernetes-id: agentsapi-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: agentsapi
  template:
    metadata:
      labels:
        app: agentsapi
        backstage.io/kubernetes-id: agentsapi-app
    spec:
      containers:
      - name: agentsapi
        image: your-acr-name.azurecr.io/your-app-name:latest # This will be replaced dynamically in the workflow
        ports:
        - containerPort: 80
