apiVersion: v1
kind: Service
metadata:
  name: agentsapi-loadbalancer
  labels:
    app: agentsapi-lb
    backstage.io/kubernetes-id: agentsapi-app
spec:
  type: LoadBalancer
  selector:
    app: agentsapi
  ports:
  - port: 80
    targetPort: 80
